language: node_js
services:
- postgresql
node_js:
- stable
- "lts/*"
matrix:
  fast_finish: true
  allow_failures:
  - node_js: stable
  - env: CMD=lint
env:
  matrix:
  - CMD=lint
  - CMD=test
script:
- yarn $CMD
notifications:
  email: false
